"""Inline the two brand marks into the client bundle.

Sources (both authoritative — taken from the products' own installations):
  - WorkBuddy:  D:\\Program\\WorkBuddy\\Assets\\Square44x44Logo.targetsize-256.png
  - Antigravity: the logo inside its official installer.exe (Google's mark)

WHY INLINE RATHER THAN A MODULE
    The browser half is loaded as a single bundle whose `require` supports only
    `react` and `react/jsx-runtime`. A sibling `icons.js` could not be imported,
    so the data URIs are written straight into `lib/client.js` between the
    BEGIN/END markers below. Re-running this script is idempotent.

The panel renders these at ~14-16px, so they are downscaled to 32px (2x for
retina) and emitted as optimized PNG data URIs — together ~4.3 KB, small enough
that avoiding a runtime fetch is worth the bytes.
"""

import base64
import io
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BUNDLE = ROOT / "lib" / "client.js"

# Where each mark comes from. The first existing path wins.
#
# The .scratch copies are the ones this repo was built from, but .scratch is
# gitignored, so a fresh clone falls back to the products' own install
# locations — which is where these were extracted from in the first place.
WORKBUDDY_SOURCES = [
    ROOT / "scripts" / "icons" / "workbuddy-256.png",
    Path(r"D:\Program\WorkBuddy\Assets\Square44x44Logo.targetsize-256.png"),
]
ANTIGRAVITY_SOURCES = [
    ROOT / "scripts" / "icons" / "antigravity-256.png",
]

TARGET = 32
BEGIN = "//#region generated: brand icons"
END = "//#endregion"


def load(path: Path) -> Image.Image:
    image = Image.open(path)
    image.load()
    return image.convert("RGBA")


def remove_white_card(image: Image.Image, threshold: int = 244) -> Image.Image:
    """Drop the flat white card the Antigravity mark sits on.

    The source PNG has transparent CORNERS but an opaque white rounded-square
    card behind the mark (measured: ~33k near-white pixels). A border flood fill
    cannot reach it, because the transparent corners do not connect to the card's
    interior through the border — so the white is removed by connected region
    instead. The mark itself is saturated (blue/orange/green), well clear of the
    threshold, so it is untouched. Regions under 200px are kept, since a small
    white area could be a highlight inside the mark.
    """
    width, height = image.size
    pixels = image.load()

    def is_card(x: int, y: int) -> bool:
        r, g, b, a = pixels[x, y]
        if a == 0:
            return False
        return r >= threshold and g >= threshold and b >= threshold

    seen = set()
    for sy in range(height):
        for sx in range(width):
            if (sx, sy) in seen or not is_card(sx, sy):
                continue
            stack = [(sx, sy)]
            region = []
            while stack:
                x, y = stack.pop()
                if (x, y) in seen:
                    continue
                seen.add((x, y))
                if not is_card(x, y):
                    continue
                region.append((x, y))
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < width and 0 <= ny < height and (nx, ny) not in seen:
                        stack.append((nx, ny))
            if len(region) < 200:
                continue
            for x, y in region:
                r, g, b, _ = pixels[x, y]
                pixels[x, y] = (r, g, b, 0)
    return image


def to_data_uri(image: Image.Image, size: int = TARGET) -> tuple[str, int]:
    buffer = io.BytesIO()
    image.resize((size, size), Image.LANCZOS).save(buffer, format="PNG", optimize=True)
    raw = buffer.getvalue()
    return "data:image/png;base64," + base64.b64encode(raw).decode("ascii"), len(raw)


def first_existing(candidates: list[Path], label: str) -> Path:
    for path in candidates:
        if path.is_file():
            return path
    raise SystemExit(
        f"could not find the {label} icon. Looked in:\n  "
        + "\n  ".join(str(p) for p in candidates)
    )


def main() -> None:
    wb_path = first_existing(WORKBUDDY_SOURCES, "WorkBuddy")
    ag_path = first_existing(ANTIGRAVITY_SOURCES, "Antigravity")
    print(f"workbuddy   <- {wb_path}")
    print(f"antigravity <- {ag_path}")

    workbuddy = load(wb_path)
    antigravity = remove_white_card(load(ag_path))

    wb_uri, wb_bytes = to_data_uri(workbuddy)
    ag_uri, ag_bytes = to_data_uri(antigravity)

    block = (
        f"{BEGIN}\n"
        "\t\t/**\n"
        "\t\t* Brand marks for each data source, inlined as data URIs.\n"
        "\t\t*\n"
        "\t\t* GENERATED by scripts/build-icons.py - do not hand-edit. Both come\n"
        "\t\t* from the products' own installations, so they are the real marks.\n"
        "\t\t* 32px source for a ~16px render.\n"
        "\t\t*/\n"
        f'\t\tconst WORKBUDDY_ICON = "{wb_uri}";\n'
        f'\t\tconst GOOGLE_ICON = "{ag_uri}";\n'
        "\t\t/** The mark for a source kind. */\n"
        "\t\tfunction sourceIcon(kind) {\n"
        "\t\t\treturn kind === KIND_GOOGLE ? GOOGLE_ICON : WORKBUDDY_ICON;\n"
        "\t\t}\n"
        f"\t\t{END}\n"
    )

    text = BUNDLE.read_text(encoding="utf-8")
    start = text.find(BEGIN)
    if start == -1:
        raise SystemExit(f"marker not found in {BUNDLE}: {BEGIN}")
    end = text.find(END, start)
    if end == -1:
        raise SystemExit(f"closing marker not found in {BUNDLE}")
    end += len(END) + 1

    BUNDLE.write_text(text[:start] + block + text[end:], encoding="utf-8")
    print(f"inlined icons into {BUNDLE}")
    print(f"  workbuddy   png {wb_bytes:>6} bytes -> {len(wb_uri):>6} chars")
    print(f"  antigravity png {ag_bytes:>6} bytes -> {len(ag_uri):>6} chars")
    print(f"  bundle now {BUNDLE.stat().st_size} bytes")


if __name__ == "__main__":
    main()
